services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile

  nginx:
    image: shark-web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot