# build stage
FROM node:lts-alpine as build-stage
USER root
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY /ssl/server.crt etc/ssl/certs
COPY /ssl/server.key etc/ssl/private
COPY /ssl/server.conf etc/nginx/conf.d
RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]